### ISSUE TITLE
Sensor broken?

### ISSUE THREAD

**Issue by FreeWillaert** [jeroendoggen/Arduino-distance-sensor-library#8]
First, I appologize because this is probably not an 'issue' with your library... but I'm looking for some help.

I'm using the GP2Y0A21YK sensor with your library. The example gives an output like below, but...
During these couple of seconds *I did not touch anything*. This same pattern comes back over and over again, even though the sensor input does not change - it's just pointing at a white wall.

Now, when I first connected the sensor I accidentally switched +5V and GND, maybe for a minute. I felt the sensor got hot and fixed the mistake.

Should I conclude the sensor is broken?

Many thanks for some advice!

Distance in centimeters: 255
Distance in centimeters: 255
Distance in centimeters: 67
Distance in centimeters: 28
Distance in centimeters: 15
Distance in centimeters: 15
Distance in centimeters: 15
Distance in centimeters: 15
Distance in centimeters: 15
Distance in centimeters: 15
Distance in centimeters: 15
Distance in centimeters: 15
Distance in centimeters: 15
Distance in centimeters: 15
Distance in centimeters: 15
Distance in centimeters: 16
Distance in centimeters: 17
Distance in centimeters: 16
Distance in centimeters: 19
Distance in centimeters: 27
Distance in centimeters: 40
Distance in centimeters: 255
Distance in centimeters: 255
Distance in centimeters: 255
Distance in centimeters: 255
Distance in centimeters: 255
Distance in centimeters: 255
Distance in centimeters: 255
Distance in centimeters: 255
Distance in centimeters: 255
Distance in centimeters: 255
Distance in centimeters: 255
Distance in centimeters: 255
Distance in centimeters: 255
Distance in centimeters: 255
Distance in centimeters: 60
Distance in centimeters: 30
Distance in centimeters: 17
Distance in centimeters: 15
Distance in centimeters: 15
Distance in centimeters: 15
Distance in centimeters: 15
Distance in centimeters: 15
Distance in centimeters: 15
Distance in centimeters: 15
Distance in centimeters: 15
Distance in centimeters: 15
Distance in centimeters: 15
Distance in centimeters: 15
Distance in centimeters: 17
Distance in centimeters: 16
Distance in centimeters: 17
Distance in centimeters: 22
Distance in centimeters: 31
Distance in centimeters: 67
Distance in centimeters: 255
Distance in centimeters: 255
Distance in centimeters: 255
Distance in centimeters: 255
Distance in centimeters: 255

**Comment by jeroendoggen** [comment]
I am afraid your sensor is broken.

**Comment by FreeWillaert** [comment]
Thanks man! :o)

On 29 June 2015 at 16:22, jeroendoggen <notifications@github.com> wrote:

> I am afraid your sensor is broken.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jeroendoggen/Arduino-distance-sensor-library/issues/8#issuecomment-116696487>
> .
>



-- 
Free

+32 498 91 44 31
Twitter: @FreeWillaert
<https://twitter.com/intent/follow?original_referer=https%3A%2F%2Fabout.twitter.com%2Fresources%2Fbuttons&region=follow_link&screen_name=FreeWillaert&tw_p=followbutton>
Website: http://sitcom.be
LinkedIn: https://www.linkedin.com/in/freewillaert
<https://www.linkedin.com/in/freewillaert>

--
By the way.....

http://facebook.com/dekaasstolp - whether you like it or not :o)


sitcom bvba
Diestsesteenweg 111
3010 Kessel-Lo
BE0895.067.696
